include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - lib/generated/intl/*.dart
    - lib/**/*.g.dart

linter:
  rules:
    prefer_single_quotes: false
    prefer_const_constructors: true
    unnecessary_final: false
